language: java
jdk: oraclejdk11

addons:
  chrome: stable

before_script:
  - wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - unzip chromedriver_linux64.zip -d /home/travis/

