language: java
jdk: oraclejdk11

addons:
  chrome: stable

before_script:
  - sudo wget http://chromedriver.storage.googleapis.com/2.24/chromedriver_linux64.zip
  - sudo unzip chromedriver_linux64.zip -d /home/
  - sudo mv chromedriver /usr/bin/chromedriver
  - sudo chown root:root /usr/bin/chromedriver
  - sudo chmod +x /usr/bin/chromedriver

